// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXzx2g5E-wD2UCHV7WnTxwBEwfNzrKTnM',
    appId: '1:236060971152:web:49e4fa868269b4859c8815',
    messagingSenderId: '236060971152',
    projectId: 'summer-project-52fb1',
    authDomain: 'summer-project-52fb1.firebaseapp.com',
    storageBucket: 'summer-project-52fb1.firebasestorage.app',
    measurementId: 'G-FDGMHJ8YXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiCL3MEh6q2-yU3rEjVaqhGYOzVpkaFPg',
    appId: '1:236060971152:android:7d319318f8b0c4399c8815',
    messagingSenderId: '236060971152',
    projectId: 'summer-project-52fb1',
    storageBucket: 'summer-project-52fb1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFHU2prBqhvmFdqpa4gmlyBlyWGf_pixM',
    appId: '1:236060971152:ios:b853c1055e25a7d39c8815',
    messagingSenderId: '236060971152',
    projectId: 'summer-project-52fb1',
    storageBucket: 'summer-project-52fb1.firebasestorage.app',
    iosBundleId: 'com.example.loboTourismManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFHU2prBqhvmFdqpa4gmlyBlyWGf_pixM',
    appId: '1:236060971152:ios:b853c1055e25a7d39c8815',
    messagingSenderId: '236060971152',
    projectId: 'summer-project-52fb1',
    storageBucket: 'summer-project-52fb1.firebasestorage.app',
    iosBundleId: 'com.example.loboTourismManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXzx2g5E-wD2UCHV7WnTxwBEwfNzrKTnM',
    appId: '1:236060971152:web:98117d2cf0bfbad79c8815',
    messagingSenderId: '236060971152',
    projectId: 'summer-project-52fb1',
    authDomain: 'summer-project-52fb1.firebaseapp.com',
    storageBucket: 'summer-project-52fb1.firebasestorage.app',
    measurementId: 'G-D87DL9PNEH',
  );
}
